version: "3"
services:

  client:
    image: client:latest
    container_name: client
    environment:
     - PSQL_URL=jdbc:postgresql://postgres:5432/
     - REPORTS_HOST=http://server:8080
     - WORKERS=2
     - POLL_DELAY_MS=500
    networks:
     - net
    depends_on: 
     - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./deployment/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432"
    networks:
     - net

  server:
    image: server:latest
    container_name: server
    environment: 
      - REPORTS_PER_SECOND=200
      - REPORTS_TOTAL=1000
      - DATA_SIZE=512
    networks:
     - net

networks:
  net:
